apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: atingupta2005/currency-exchange
        imagePullPolicy: Always
        name: currency-exchange
        ports:
        - name: liveness-port
          containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  ports:
   - port: 8000
     protocol: TCP
     targetPort: 8000
  selector:
    app: currency-exchange
  type: LoadBalancer
